objective:
  - Crowdsourcing

dataset: # dataset to run benchmark on
  - bluebirds
  - adultcontent2
  - rte
solver: # list of example solvers to do benchmark
  - peerannot[strategy=MV]
  - peerannot[strategy=DS]
  - peerannot[strategy=GLAD]
  - peerannot[strategy=WDS]
  - crowd-kit
  - FDS
  - DS-mcmc
# note: use more repetitions to have quantiles on the plot
n-repetitions: 1
max-runs: 5
timeout: 15m